import * as React from "react"
import { cn } from "cn"
import {
  ActivityIcon,
  ArrowDownToLineIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpFromLineIcon,
  BanknoteIcon,
  BellIcon,
  BlocksIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  Building2Icon,
  CalendarCheckIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarRangeIcon,
  CarFrontIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleDollarSignIcon,
  CircleSlash2Icon,
  CircleUserIcon,
  CloudDownloadIcon,
  CodeIcon,
  CoinsIcon,
  Columns3Icon,
  CopyIcon,
  CornerDownRightIcon,
  CreditCardIcon,
  DownloadIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileDownIcon,
  FileIcon,
  FileTextIcon,
  FingerprintIcon,
  FlagIcon,
  FolderTreeIcon,
  GemIcon,
  GiftIcon,
  GlobeIcon,
  HandCoinsIcon,
  HeadsetIcon,
  HourglassIcon,
  HouseIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  KeyRoundIcon,
  KeySquareIcon,
  LandmarkIcon,
  LanguagesIcon,
  LayersIcon,
  LibraryBigIcon,
  ListChecksIcon,
  ListFilterIcon,
  LoaderCircleIcon,
  LockIcon,
  LockOpenIcon,
  LogInIcon,
  LogOutIcon,
  MailCheckIcon,
  MailIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  MessageCircleQuestionIcon,
  MessageSquareIcon,
  MonitorIcon,
  MonitorSmartphoneIcon,
  MoonIcon,
  MoreHorizontalIcon,
  NavigationIcon,
  NewspaperIcon,
  NotebookTabsIcon,
  PackageCheckIcon,
  PackageIcon,
  PackagePlusIcon,
  PackageXIcon,
  PaintbrushIcon,
  PaletteIcon,
  PencilIcon,
  PercentIcon,
  PhoneCallIcon,
  PlusIcon,
  PrinterIcon,
  ReceiptIcon,
  RefreshCwIcon,
  RotateCcwIcon,
  RouteIcon,
  ScaleIcon,
  SearchIcon,
  SettingsIcon,
  Share2Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  SparklesIcon,
  StarIcon,
  StoreIcon,
  SunIcon,
  TagIcon,
  TicketIcon,
  Trash2Icon,
  TrendingUpIcon,
  TriangleAlertIcon,
  TruckIcon,
  UploadIcon,
  UserCircleIcon,
  UserPlusIcon,
  UserRoundPlusIcon,
  UsersIcon,
  WalletIcon,
  WebhookIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react"

/* Semantic icon registry, from the PM prototype. Screens name a meaning, never a glyph, so swapping one is a single edit here. */
const ICON_GROUPS = {
  "Navigation & objects": {
    dashboard: HouseIcon,
    orders: ShoppingCartIcon,
    products: ShoppingBagIcon,
    categories: FolderTreeIcon,
    brands: TagIcon,
    collections: LayersIcon,
    attributes: SlidersHorizontalIcon,
    reviews: StarIcon,
    questions: MessageCircleQuestionIcon,
    customers: UsersIcon,
    customer: UserCircleIcon,
    vendors: StoreIcon,
    invoices: FileTextIcon,
    preorders: CalendarClockIcon,
    refunds: RotateCcwIcon,
    returns: PackageXIcon,
    abandonedCart: CircleSlash2Icon,
    coupons: TicketIcon,
    marketing: MegaphoneIcon,
    blogs: NewspaperIcon,
    pages: FileIcon,
    themes: PaintbrushIcon,
    media: ImageIcon,
    abuse: FlagIcon,
  },
  Fulfilment: {
    shipping: TruckIcon,
    delivery: NavigationIcon,
    drivers: CarFrontIcon,
    locations: MapPinIcon,
    fulfilment: PackageCheckIcon,
  },
  Money: {
    plan: GemIcon,
    billing: CreditCardIcon,
    payments: WalletIcon,
    payouts: BanknoteIcon,
    vendorPayouts: HandCoinsIcon,
    taxes: ReceiptIcon,
    currency: CircleDollarSignIcon,
    commission: PercentIcon,
    revenue: TrendingUpIcon,
    ledgerbook: NotebookTabsIcon,
    cash: BanknoteIcon,
    yours: CoinsIcon,
    taxOwed: LandmarkIcon,
    onItsWay: HourglassIcon,
    arriving: ArrowDownToLineIcon,
    leaving: ArrowUpFromLineIcon,
    comingUp: CalendarClockIcon,
    whereItWent: RouteIcon,
    bank: LandmarkIcon,
    inTransit: HourglassIcon,
    held: LandmarkIcon,
    settlement: ArrowDownToLineIcon,
    reconcile: RouteIcon,
    period: CalendarRangeIcon,
    chargeback: ShieldAlertIcon,
    reserve: LockIcon,
    pending: HourglassIcon,
    deposited: CircleCheckIcon,
    ledgerEntry: BookOpenTextIcon,
    columns: Columns3Icon,
    locked: LockIcon,
    unlock: LockOpenIcon,
  },
  Platform: {
    settings: SettingsIcon,
    users: UsersIcon,
    permissions: ShieldCheckIcon,
    integrations: BlocksIcon,
    webhooks: WebhookIcon,
    api: CodeIcon,
    ai: SparklesIcon,
    domains: GlobeIcon,
    languages: LanguagesIcon,
    markets: MapIcon,
    seo: TrendingUpIcon,
    redirects: CornerDownRightIcon,
    events: ActivityIcon,
    notifications: BellIcon,
    policies: ScaleIcon,
    setupGuide: ListChecksIcon,
    brandAppearance: PaletteIcon,
    onboarding: UserPlusIcon,
    resources: LibraryBigIcon,
    support: HeadsetIcon,
    supportPin: KeyRoundIcon,
    roadmap: MessageSquareIcon,
    docs: BookOpenIcon,
    changelog: GiftIcon,
    scheduleCall: PhoneCallIcon,
    team: UsersIcon,
    referral: GiftIcon,
    signOut: LogOutIcon,
  },
  "Account & security": {
    passkey: FingerprintIcon,
    password: KeySquareIcon,
    twoStep: ShieldCheckIcon,
    device: MonitorSmartphoneIcon,
    phone: SmartphoneIcon,
    email: MailIcon,
    profile: CircleUserIcon,
    status: ActivityIcon,
  },
  Actions: {
    add: PlusIcon,
    edit: PencilIcon,
    delete: Trash2Icon,
    duplicate: CopyIcon,
    export: DownloadIcon,
    import: UploadIcon,
    search: SearchIcon,
    filter: ListFilterIcon,
    more: MoreHorizontalIcon,
    external: ExternalLinkIcon,
    back: ArrowLeftIcon,
    forward: ArrowRightIcon,
    close: XIcon,
    check: CheckIcon,
    expand: ChevronDownIcon,
    collapse: ChevronUpIcon,
    next: ChevronRightIcon,
    prev: ChevronLeftIcon,
    print: PrinterIcon,
    refresh: RefreshCwIcon,
    impersonate: LogInIcon,
  },
  Feedback: {
    info: InfoIcon,
    warning: TriangleAlertIcon,
    error: CircleAlertIcon,
    success: CircleCheckIcon,
    empty: InboxIcon,
    loading: LoaderCircleIcon,
  },
  "Onboarding & appearance": {
    taskEmail: MailCheckIcon,
    taskProduct: PackagePlusIcon,
    taskPayment: CreditCardIcon,
    taskDelivery: TruckIcon,
    taskFiles: FileDownIcon,
    taskAvailability: CalendarCheckIcon,
    taskVendor: UserRoundPlusIcon,
    taskStore: StoreIcon,
    storefront: StoreIcon,
    share: Share2Icon,
    reveal: EyeIcon,
    conceal: EyeOffIcon,
    themeLight: SunIcon,
    themeDark: MoonIcon,
    themeSystem: MonitorIcon,
    sellNotYet: SparklesIcon,
    sellOwnSite: GlobeIcon,
    sellMarketplace: StoreIcon,
    sellInPerson: Building2Icon,
    goodsPhysical: PackageIcon,
    goodsDigital: CloudDownloadIcon,
    goodsServices: CalendarDaysIcon,
    goodsPod: ShirtIcon,
    grow: TrendingUpIcon,
    domain: GlobeIcon,
    visitors: EyeIcon,
  },
} satisfies Record<string, Record<string, LucideIcon>>

type IconGroups = typeof ICON_GROUPS
type IconName = {
  [G in keyof IconGroups]: keyof IconGroups[G]
}[keyof IconGroups] &
  string

const ICONS = Object.assign({}, ...Object.values(ICON_GROUPS)) as Record<
  IconName,
  LucideIcon
>

type IconProps = Omit<React.ComponentProps<LucideIcon>, "ref"> & {
  name: IconName
  /** Accessible name; without it the icon is decorative. */
  label?: string
}

function Icon({
  name,
  label,
  size = 16,
  strokeWidth = 1.7,
  className,
  ...props
}: IconProps) {
  const Glyph = ICONS[name]
  return (
    <Glyph
      data-slot="icon"
      data-icon-name={name}
      size={size}
      strokeWidth={strokeWidth}
      className={cn("shrink-0", className)}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
      {...props}
    />
  )
}

export { Icon, ICONS, ICON_GROUPS, type IconName, type IconProps }
