import * as React from "react"
import { cn } from "cn"
import type { IconType } from "react-icons"
import { PiSlidersHorizontal } from "react-icons/pi"
import { TbShoppingCartX } from "react-icons/tb"
import {
  FiActivity as ActivityIcon,
  FiArrowLeft as ArrowLeftIcon,
  FiArrowRight as ArrowRightIcon,
  FiBell as BellIcon,
  FiBookOpen as BookOpenIcon,
  FiCalendar as CalendarDaysIcon,
  FiCheck as CheckIcon,
  FiChevronDown as ChevronDownIcon,
  FiChevronLeft as ChevronLeftIcon,
  FiChevronRight as ChevronRightIcon,
  FiChevronUp as ChevronUpIcon,
  FiAlertCircle as CircleAlertIcon,
  FiCheckCircle as CircleCheckIcon,
  FiDollarSign as CircleDollarSignIcon,
  FiUser as CircleUserIcon,
  FiDownloadCloud as CloudDownloadIcon,
  FiCode as CodeIcon,
  FiColumns as Columns3Icon,
  FiCopy as CopyIcon,
  FiCornerDownRight as CornerDownRightIcon,
  FiCreditCard as CreditCardIcon,
  FiDownload as DownloadIcon,
  FiExternalLink as ExternalLinkIcon,
  FiEye as EyeIcon,
  FiEyeOff as EyeOffIcon,
  FiFile as FileIcon,
  FiFileText as FileTextIcon,
  FiFlag as FlagIcon,
  FiGift as GiftIcon,
  FiGlobe as GlobeIcon,
  FiHome as HouseIcon,
  FiImage as ImageIcon,
  FiInbox as InboxIcon,
  FiInfo as InfoIcon,
  FiKey as KeyRoundIcon,
  FiLayers as LayersIcon,
  FiFilter as ListFilterIcon,
  FiLock as LockIcon,
  FiLogIn as LogInIcon,
  FiLogOut as LogOutIcon,
  FiMail as MailIcon,
  FiMap as MapIcon,
  FiMapPin as MapPinIcon,
  FiHelpCircle as MessageCircleQuestionIcon,
  FiMessageSquare as MessageSquareIcon,
  FiMonitor as MonitorIcon,
  FiMoon as MoonIcon,
  FiMoreHorizontal as MoreHorizontalIcon,
  FiNavigation as NavigationIcon,
  FiPackage as PackageIcon,
  FiEdit2 as PencilIcon,
  FiPercent as PercentIcon,
  FiPhoneCall as PhoneCallIcon,
  FiPlus as PlusIcon,
  FiPrinter as PrinterIcon,
  FiRefreshCw as RefreshCwIcon,
  FiRotateCcw as RotateCcwIcon,
  FiSearch as SearchIcon,
  FiSettings as SettingsIcon,
  FiShare2 as Share2Icon,
  FiShoppingBag as ShoppingBagIcon,
  FiShoppingCart as ShoppingCartIcon,
  FiSliders as SlidersHorizontalIcon,
  FiSmartphone as SmartphoneIcon,
  FiStar as StarIcon,
  FiSun as SunIcon,
  FiTag as TagIcon,
  FiTrash2 as Trash2Icon,
  FiTrendingUp as TrendingUpIcon,
  FiAlertTriangle as TriangleAlertIcon,
  FiTruck as TruckIcon,
  FiUpload as UploadIcon,
  FiUser as UserCircleIcon,
  FiUserPlus as UserPlusIcon,
  FiUsers as UsersIcon,
  FiX as XIcon,
} from "react-icons/fi"
import {
  LuArrowDownToLine as ArrowDownToLineIcon,
  LuArrowUpFromLine as ArrowUpFromLineIcon,
  LuBanknote as BanknoteIcon,
  LuBookOpenText as BookOpenTextIcon,
  LuBuilding2 as Building2Icon,
  LuCalendarCheck as CalendarCheckIcon,
  LuCalendarClock as CalendarClockIcon,
  LuCalendarRange as CalendarRangeIcon,
  LuCarFront as CarFrontIcon,
  LuCoins as CoinsIcon,
  LuFileDown as FileDownIcon,
  LuFingerprint as FingerprintIcon,
  LuFolderTree as FolderTreeIcon,
  LuGem as GemIcon,
  LuHandCoins as HandCoinsIcon,
  LuHourglass as HourglassIcon,
  LuKeySquare as KeySquareIcon,
  LuLandmark as LandmarkIcon,
  LuLanguages as LanguagesIcon,
  LuLibraryBig as LibraryBigIcon,
  LuLoaderCircle as LoaderCircleIcon,
  LuLockOpen as LockOpenIcon,
  LuMailCheck as MailCheckIcon,
  LuMegaphone as MegaphoneIcon,
  LuMonitorSmartphone as MonitorSmartphoneIcon,
  LuNewspaper as NewspaperIcon,
  LuNotebookTabs as NotebookTabsIcon,
  LuPackageCheck as PackageCheckIcon,
  LuPackagePlus as PackagePlusIcon,
  LuPackageX as PackageXIcon,
  LuPalette as PaletteIcon,
  LuReceipt as ReceiptIcon,
  LuRoute as RouteIcon,
  LuScale as ScaleIcon,
  LuShieldAlert as ShieldAlertIcon,
  LuShieldCheck as ShieldCheckIcon,
  LuShirt as ShirtIcon,
  LuSparkles as SparklesIcon,
  LuStore as StoreIcon,
  LuTicket as TicketIcon,
  LuUserRoundPlus as UserRoundPlusIcon,
  LuWallet as WalletIcon,
  LuWebhook as WebhookIcon,
} from "react-icons/lu"

/* Semantic icon registry. Glyphs follow the dashboard (Feather via react-icons, its sidebar choices first); Lucide fills gaps Feather lacks. */
const ICON_GROUPS = {
  "Navigation & objects": {
    dashboard: HouseIcon,
    orders: ShoppingCartIcon,
    products: ShoppingBagIcon,
    categories: FolderTreeIcon,
    brands: TagIcon,
    collections: LayersIcon,
    attributes: SlidersHorizontalIcon,
    reviews: StarIcon,
    questions: MessageCircleQuestionIcon,
    customers: UsersIcon,
    customer: UserCircleIcon,
    vendors: UserCircleIcon,
    invoices: FileTextIcon,
    preorders: CalendarClockIcon,
    refunds: RotateCcwIcon,
    returns: PackageXIcon,
    abandonedCart: TbShoppingCartX,
    coupons: TicketIcon,
    marketing: MegaphoneIcon,
    blogs: NewspaperIcon,
    pages: FileIcon,
    themes: SlidersHorizontalIcon,
    media: ImageIcon,
    abuse: FlagIcon,
  },
  Fulfilment: {
    shipping: TruckIcon,
    delivery: NavigationIcon,
    drivers: CarFrontIcon,
    locations: MapPinIcon,
    fulfilment: PackageCheckIcon,
  },
  Money: {
    plan: GemIcon,
    billing: CreditCardIcon,
    payments: WalletIcon,
    payouts: BanknoteIcon,
    vendorPayouts: HandCoinsIcon,
    taxes: ReceiptIcon,
    currency: CircleDollarSignIcon,
    commission: PercentIcon,
    revenue: TrendingUpIcon,
    ledgerbook: NotebookTabsIcon,
    cash: BanknoteIcon,
    yours: CoinsIcon,
    taxOwed: LandmarkIcon,
    onItsWay: HourglassIcon,
    arriving: ArrowDownToLineIcon,
    leaving: ArrowUpFromLineIcon,
    comingUp: CalendarClockIcon,
    whereItWent: RouteIcon,
    bank: LandmarkIcon,
    inTransit: HourglassIcon,
    held: LandmarkIcon,
    settlement: ArrowDownToLineIcon,
    reconcile: RouteIcon,
    period: CalendarRangeIcon,
    chargeback: ShieldAlertIcon,
    reserve: LockIcon,
    pending: HourglassIcon,
    deposited: CircleCheckIcon,
    ledgerEntry: BookOpenTextIcon,
    columns: Columns3Icon,
    locked: LockIcon,
    unlock: LockOpenIcon,
  },
  Platform: {
    settings: SettingsIcon,
    users: UsersIcon,
    permissions: ShieldCheckIcon,
    integrations: LayersIcon,
    webhooks: WebhookIcon,
    api: CodeIcon,
    ai: SparklesIcon,
    domains: GlobeIcon,
    languages: LanguagesIcon,
    markets: MapIcon,
    seo: TrendingUpIcon,
    redirects: CornerDownRightIcon,
    events: ActivityIcon,
    notifications: BellIcon,
    policies: ScaleIcon,
    setupGuide: PiSlidersHorizontal,
    brandAppearance: PaletteIcon,
    onboarding: UserPlusIcon,
    resources: LibraryBigIcon,
    support: MessageCircleQuestionIcon,
    supportPin: KeyRoundIcon,
    roadmap: MessageSquareIcon,
    docs: BookOpenIcon,
    changelog: GiftIcon,
    scheduleCall: PhoneCallIcon,
    team: UsersIcon,
    referral: GiftIcon,
    signOut: LogOutIcon,
  },
  "Account & security": {
    passkey: FingerprintIcon,
    password: KeySquareIcon,
    twoStep: ShieldCheckIcon,
    device: MonitorSmartphoneIcon,
    phone: SmartphoneIcon,
    email: MailIcon,
    profile: CircleUserIcon,
    status: ActivityIcon,
  },
  Actions: {
    add: PlusIcon,
    edit: PencilIcon,
    delete: Trash2Icon,
    duplicate: CopyIcon,
    export: DownloadIcon,
    import: UploadIcon,
    search: SearchIcon,
    filter: ListFilterIcon,
    more: MoreHorizontalIcon,
    external: ExternalLinkIcon,
    back: ArrowLeftIcon,
    forward: ArrowRightIcon,
    close: XIcon,
    check: CheckIcon,
    expand: ChevronDownIcon,
    collapse: ChevronUpIcon,
    next: ChevronRightIcon,
    prev: ChevronLeftIcon,
    print: PrinterIcon,
    refresh: RefreshCwIcon,
    impersonate: LogInIcon,
  },
  Feedback: {
    info: InfoIcon,
    warning: TriangleAlertIcon,
    error: CircleAlertIcon,
    success: CircleCheckIcon,
    empty: InboxIcon,
    loading: LoaderCircleIcon,
  },
  "Onboarding & appearance": {
    taskEmail: MailCheckIcon,
    taskProduct: PackagePlusIcon,
    taskPayment: CreditCardIcon,
    taskDelivery: TruckIcon,
    taskFiles: FileDownIcon,
    taskAvailability: CalendarCheckIcon,
    taskVendor: UserRoundPlusIcon,
    taskStore: StoreIcon,
    storefront: StoreIcon,
    share: Share2Icon,
    reveal: EyeIcon,
    conceal: EyeOffIcon,
    themeLight: SunIcon,
    themeDark: MoonIcon,
    themeSystem: MonitorIcon,
    sellNotYet: SparklesIcon,
    sellOwnSite: GlobeIcon,
    sellMarketplace: StoreIcon,
    sellInPerson: Building2Icon,
    goodsPhysical: PackageIcon,
    goodsDigital: CloudDownloadIcon,
    goodsServices: CalendarDaysIcon,
    goodsPod: ShirtIcon,
    grow: TrendingUpIcon,
    domain: GlobeIcon,
    visitors: EyeIcon,
  },
} satisfies Record<string, Record<string, IconType>>

type IconGroups = typeof ICON_GROUPS
type IconName = {
  [G in keyof IconGroups]: keyof IconGroups[G]
}[keyof IconGroups] &
  string

const ICONS = Object.assign({}, ...Object.values(ICON_GROUPS)) as Record<
  IconName,
  IconType
>

type IconProps = Omit<React.ComponentProps<IconType>, "ref"> & {
  name: IconName
  /** Accessible name; without it the icon is decorative. */
  label?: string
}

function Icon({
  name,
  label,
  size = 16,
  strokeWidth = 2,
  className,
  ...props
}: IconProps) {
  const Glyph = ICONS[name]
  return (
    <Glyph
      data-slot="icon"
      data-icon-name={name}
      size={size}
      strokeWidth={strokeWidth}
      className={cn("shrink-0", className)}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
      {...props}
    />
  )
}

export { Icon, ICONS, ICON_GROUPS, type IconName, type IconProps }
