// Regenerates the Claude skill's reference files from source: pnpm skill:refs
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "..")
const out = path.join(root, "plugin/skills/flycommerce-ui/references")
mkdirSync(out, { recursive: true })

const header = (title) =>
  `# ${title}\n\n<!-- Generated by scripts/skill-refs.mjs from the library source. Do not edit by hand. -->\n\n`

function exportsOf(file) {
  const src = readFileSync(file, "utf8")
  const names = []
  for (const block of src.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const raw of block[1].split(",")) {
      const part = raw.trim()
      if (!part) continue
      const isType = part.startsWith("type ")
      const name = part.replace(/^type\s+/, "").split(/\s+as\s+/).pop().trim()
      names.push(isType ? `type ${name}` : name)
    }
  }
  return names
}

function docOf(file) {
  const src = readFileSync(file, "utf8")
  const m = src.match(/\/\*\*\s*([^*][^\n]*?)\s*\*\/\s*\n\s*function\s+[A-Z]/)
  return m ? m[1] : ""
}

let exportsMd = header("@flycommerce/ui exports")
exportsMd += "Everything is imported from the package root: `import { Button, DataTable } from \"@flycommerce/ui\"`.\n\n"
exportsMd += "## Patterns (FlyCommerce composites)\n\n| Module | Exports | Notes |\n|---|---|---|\n"
for (const f of readdirSync(path.join(root, "src/components")).filter((f) => f.endsWith(".tsx")).sort()) {
  const file = path.join(root, "src/components", f)
  exportsMd += `| \`${f.replace(".tsx", "")}\` | ${exportsOf(file).map((n) => `\`${n}\``).join(", ")} | ${docOf(file)} |\n`
}
exportsMd += "\n## Primitives (shadcn, restyled)\n\n| Module | Exports |\n|---|---|\n"
const skip = new Set(["attachment", "bubble", "marker", "message", "message-scroller", "questionnaire"])
for (const f of readdirSync(path.join(root, "src/components/ui")).filter((f) => f.endsWith(".tsx")).sort()) {
  const id = f.replace(".tsx", "")
  if (skip.has(id)) continue
  exportsMd += `| \`${id}\` | ${exportsOf(path.join(root, "src/components/ui", f)).map((n) => `\`${n}\``).join(", ")} |\n`
}
writeFileSync(path.join(out, "exports.md"), exportsMd)

const iconSrc = readFileSync(path.join(root, "src/components/icon.tsx"), "utf8")
const groupsBody = iconSrc.slice(iconSrc.indexOf("const ICON_GROUPS = {"), iconSrc.indexOf("} satisfies"))
let iconsMd = header("Icon names")
iconsMd += "Use `<Icon name=\"…\" />` with one of these names. Never import a lucide icon in a screen.\n\n"
for (const g of groupsBody.matchAll(/^\s{2}(?:"([^"]+)"|(\w+)):\s*\{([^}]*)\}/gm)) {
  const [, quoted, bare, body] = g
  const names = [...body.matchAll(/^\s*"?([\w-]+)"?:\s*(\w+)/gm)].map((m) => `\`${m[1]}\` (${m[2].replace(/Icon$/, "")})`)
  iconsMd += `## ${quoted ?? bare}\n\n${names.join(", ")}\n\n`
}
writeFileSync(path.join(out, "icons.md"), iconsMd)

const theme = readFileSync(path.join(root, "src/styles/theme.css"), "utf8")
const light = theme.slice(theme.indexOf(":root {"), theme.indexOf("}", theme.indexOf(":root {")))
let tokensMd = header("Design tokens")
tokensMd += "Values live only in `src/styles/theme.css`. In code, use the Tailwind utility (`bg-primary`, `text-muted-foreground`, `border-border`, `shadow-1`, `rounded-control`), never the value.\n\n| Token | Light value | Note |\n|---|---|---|\n"
for (const m of light.matchAll(/^\s*--([\w-]+):\s*([^;]+);\s*(?:\/\*\s*(.*?)\s*\*\/)?/gm)) {
  tokensMd += `| \`--${m[1]}\` | \`${m[2].trim()}\` | ${m[3] ?? ""} |\n`
}
writeFileSync(path.join(out, "tokens.md"), tokensMd)

console.log("skill references written to", path.relative(root, out))
