import * as React from "react"
import type { IconType } from "react-icons"
import {
  FiCircle as CircleIcon,
  FiAlignLeft as AlignLeftIcon,
  FiBell as BellIcon,
  FiCalendar as CalendarIcon,
  FiCalendar as CalendarDaysIcon,
  FiChevronsRight as ChevronsRightIcon,
  FiCheckCircle as CircleCheckIcon,
  FiUser as CircleUserIcon,
  FiColumns as Columns3Icon,
  FiCommand as CommandIcon,
  FiCopy as CopyIcon,
  FiCreditCard as CreditCardIcon,
  FiFolderPlus as FolderPlusIcon,
  FiHome as HouseIcon,
  FiImage as ImageIcon,
  FiInbox as InboxIcon,
  FiInfo as InfoIcon,
  FiKey as KeyRoundIcon,
  FiLayers as LayersIcon,
  FiList as ListIcon,
  FiFilter as ListFilterIcon,
  FiLoader as LoaderIcon,
  FiMenu as MenuIcon,
  FiMessageSquare as MessageSquareIcon,
  FiNavigation as NavigationIcon,
  FiPackage as PackageIcon,
  FiSidebar as PanelLeftIcon,
  FiSave as SaveIcon,
  FiSearch as SearchIcon,
  FiSliders as SlidersHorizontalIcon,
  FiStar as StarIcon,
  FiTable as TableIcon,
  FiToggleLeft as ToggleLeftIcon,
  FiToggleRight as ToggleRightIcon,
  FiTrendingUp as TrendingUpIcon,
  FiSquare as SquareIcon,
  FiAlertTriangle as TriangleAlertIcon,
  FiType as TypeIcon,
  FiUpload as UploadIcon,
} from "react-icons/fi"
import {
  LuBot as BotIcon,
  LuAppWindow as AppWindowIcon,
  LuAppWindowMac as AppWindowMacIcon,
  LuAsterisk as AsteriskIcon,
  LuBadge as BadgeIcon,
  LuChartColumn as ChartColumnIcon,
  LuChevronsDownUp as ChevronsDownUpIcon,
  LuChevronsUpDown as ChevronsUpDownIcon,
  LuCircleDot as CircleDotIcon,
  LuColumns2 as Columns2Icon,
  LuEllipsis as EllipsisIcon,
  LuFolderTree as FolderTreeIcon,
  LuGalleryHorizontal as GalleryHorizontalIcon,
  LuGalleryHorizontalEnd as GalleryHorizontalEndIcon,
  LuGauge as GaugeIcon,
  LuGripVertical as GripVerticalIcon,
  LuImagePlus as ImagePlusIcon,
  LuImages as ImagesIcon,
  LuKeyboard as KeyboardIcon,
  LuListChecks as ListChecksIcon,
  LuListOrdered as ListOrderedIcon,
  LuListTree as ListTreeIcon,
  LuMessageSquareWarning as MessageSquareWarningIcon,
  LuMousePointerClick as MousePointerClickIcon,
  LuOctagonAlert as OctagonAlertIcon,
  LuPalette as PaletteIcon,
  LuPanelRight as PanelRightIcon,
  LuPanelTop as PanelTopIcon,
  LuPanelsTopLeft as PanelsTopLeftIcon,
  LuPilcrow as PilcrowIcon,
  LuRatio as RatioIcon,
  LuRectangleEllipsis as RectangleEllipsisIcon,
  LuRectangleHorizontal as RectangleHorizontalIcon,
  LuScroll as ScrollIcon,
  LuShapes as ShapesIcon,
  LuSquareSplitHorizontal as SquareSplitHorizontalIcon,
  LuSquareCheck as SquareCheckIcon,
  LuTable2 as Table2Icon,
  LuTags as TagsIcon,
  LuTextCursorInput as TextCursorInputIcon,
  LuTextSearch as TextSearchIcon,
} from "react-icons/lu"

// Sidebar icons, most visible when the sidebar is collapsed.
const ICONS: Record<string, IconType> = {
  welcome: HouseIcon,
  installation: PackageIcon,
  "claude-code": BotIcon,
  typography: TypeIcon,
  colors: PaletteIcon,
  icons: ShapesIcon,
  "card-brand-icon": CreditCardIcon,
  "page-header": PanelTopIcon,
  "data-table": TableIcon,
  "data-table-reorder": GripVerticalIcon,
  "data-table-tree": ListTreeIcon,
  "confirm-dialog": MessageSquareWarningIcon,
  "save-bar": SaveIcon,
  "search-input": SearchIcon,
  "stat-card": TrendingUpIcon,
  "icon-chip": SquareIcon,
  "radio-card": CircleDotIcon,
  "switch-field": ToggleRightIcon,
  "nav-tabs": PanelsTopLeftIcon,
  "segmented-control": SquareSplitHorizontalIcon,
  "async-combobox": TextSearchIcon,
  "tag-input": TagsIcon,
  "password-input": KeyRoundIcon,
  "date-picker": CalendarDaysIcon,
  "tree-select": FolderTreeIcon,
  "rich-select": ListChecksIcon,
  "option-list-editor": ListOrderedIcon,
  "rich-text-editor": PilcrowIcon,
  "media-picker": ImagePlusIcon,
  "media-page": ImagesIcon,
  "media-parts": GalleryHorizontalIcon,
  dropzone: UploadIcon,
  "copy-button": CopyIcon,
  "info-tooltip": InfoIcon,
  "loading-overlay": LoaderIcon,
  rating: StarIcon,
  image: ImageIcon,
  "status-badge": CircleCheckIcon,
  button: MousePointerClickIcon,
  "button-group": Columns3Icon,
  toggle: ToggleLeftIcon,
  alert: TriangleAlertIcon,
  toast: BellIcon,
  progress: GaugeIcon,
  empty: InboxIcon,
  input: TextCursorInputIcon,
  "input-group": RectangleEllipsisIcon,
  textarea: AlignLeftIcon,
  select: ChevronsUpDownIcon,
  combobox: ListFilterIcon,
  checkbox: SquareCheckIcon,
  slider: SlidersHorizontalIcon,
  "input-otp": AsteriskIcon,
  calendar: CalendarIcon,
  badge: BadgeIcon,
  avatar: CircleUserIcon,
  card: RectangleHorizontalIcon,
  table: Table2Icon,
  item: ListIcon,
  kbd: KeyboardIcon,
  chart: ChartColumnIcon,
  carousel: GalleryHorizontalEndIcon,
  "aspect-ratio": RatioIcon,
  tabs: AppWindowIcon,
  accordion: ChevronsDownUpIcon,
  "scroll-area": ScrollIcon,
  resizable: Columns2Icon,
  dialog: AppWindowMacIcon,
  "modal-figma": FolderPlusIcon,
  "modal-use-cases": LayersIcon,
  "alert-dialog": OctagonAlertIcon,
  sheet: PanelRightIcon,
  popover: MessageSquareIcon,
  "dropdown-menu": MenuIcon,
  command: CommandIcon,
  breadcrumb: ChevronsRightIcon,
  pagination: EllipsisIcon,
  "navigation-menu": NavigationIcon,
  sidebar: PanelLeftIcon,
}

export function DemoIcon({ id }: { id: string }) {
  return React.createElement(ICONS[id] ?? CircleIcon, { "aria-hidden": true })
}
