import * as React from "react"
import {
  CircleIcon,
  AlignLeftIcon,
  AppWindowIcon,
  AppWindowMacIcon,
  AsteriskIcon,
  BadgeIcon,
  BellIcon,
  CalendarIcon,
  CalendarDaysIcon,
  ChartColumnIcon,
  ChevronsDownUpIcon,
  ChevronsRightIcon,
  ChevronsUpDownIcon,
  CircleCheckIcon,
  CircleDotIcon,
  CircleUserIcon,
  Columns2Icon,
  Columns3Icon,
  CommandIcon,
  CopyIcon,
  EllipsisIcon,
  FolderPlusIcon,
  FolderTreeIcon,
  GalleryHorizontalIcon,
  GalleryHorizontalEndIcon,
  GaugeIcon,
  GripVerticalIcon,
  HouseIcon,
  ImageIcon,
  ImagePlusIcon,
  ImagesIcon,
  InboxIcon,
  InfoIcon,
  KeyRoundIcon,
  KeyboardIcon,
  LayersIcon,
  ListIcon,
  ListChecksIcon,
  ListFilterIcon,
  ListOrderedIcon,
  ListTreeIcon,
  LoaderIcon,
  MenuIcon,
  MessageSquareIcon,
  MessageSquareWarningIcon,
  MousePointerClickIcon,
  NavigationIcon,
  OctagonAlertIcon,
  PackageIcon,
  PaletteIcon,
  PanelLeftIcon,
  PanelRightIcon,
  PanelTopIcon,
  PanelsTopLeftIcon,
  PilcrowIcon,
  RatioIcon,
  RectangleEllipsisIcon,
  RectangleHorizontalIcon,
  SaveIcon,
  ScrollIcon,
  SearchIcon,
  ShapesIcon,
  SlidersHorizontalIcon,
  SquareCheckIcon,
  StarIcon,
  TableIcon,
  Table2Icon,
  TagsIcon,
  TextCursorInputIcon,
  TextSearchIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
  TrendingUpIcon,
  TriangleAlertIcon,
  TypeIcon,
  UploadIcon,
  type LucideIcon,
} from "lucide-react"

// Sidebar icons, most visible when the sidebar is collapsed.
const ICONS: Record<string, LucideIcon> = {
  welcome: HouseIcon,
  installation: PackageIcon,
  typography: TypeIcon,
  colors: PaletteIcon,
  icons: ShapesIcon,
  "page-header": PanelTopIcon,
  "data-table": TableIcon,
  "data-table-reorder": GripVerticalIcon,
  "data-table-tree": ListTreeIcon,
  "confirm-dialog": MessageSquareWarningIcon,
  "save-bar": SaveIcon,
  "search-input": SearchIcon,
  "stat-card": TrendingUpIcon,
  "radio-card": CircleDotIcon,
  "switch-field": ToggleRightIcon,
  "nav-tabs": PanelsTopLeftIcon,
  "async-combobox": TextSearchIcon,
  "tag-input": TagsIcon,
  "password-input": KeyRoundIcon,
  "date-picker": CalendarDaysIcon,
  "tree-select": FolderTreeIcon,
  "rich-select": ListChecksIcon,
  "option-list-editor": ListOrderedIcon,
  "rich-text-editor": PilcrowIcon,
  "media-picker": ImagePlusIcon,
  "media-page": ImagesIcon,
  "media-parts": GalleryHorizontalIcon,
  dropzone: UploadIcon,
  "copy-button": CopyIcon,
  "info-tooltip": InfoIcon,
  "loading-overlay": LoaderIcon,
  rating: StarIcon,
  image: ImageIcon,
  "status-badge": CircleCheckIcon,
  button: MousePointerClickIcon,
  "button-group": Columns3Icon,
  toggle: ToggleLeftIcon,
  alert: TriangleAlertIcon,
  toast: BellIcon,
  progress: GaugeIcon,
  empty: InboxIcon,
  input: TextCursorInputIcon,
  "input-group": RectangleEllipsisIcon,
  textarea: AlignLeftIcon,
  select: ChevronsUpDownIcon,
  combobox: ListFilterIcon,
  checkbox: SquareCheckIcon,
  slider: SlidersHorizontalIcon,
  "input-otp": AsteriskIcon,
  calendar: CalendarIcon,
  badge: BadgeIcon,
  avatar: CircleUserIcon,
  card: RectangleHorizontalIcon,
  table: Table2Icon,
  item: ListIcon,
  kbd: KeyboardIcon,
  chart: ChartColumnIcon,
  carousel: GalleryHorizontalEndIcon,
  "aspect-ratio": RatioIcon,
  tabs: AppWindowIcon,
  accordion: ChevronsDownUpIcon,
  "scroll-area": ScrollIcon,
  resizable: Columns2Icon,
  dialog: AppWindowMacIcon,
  "modal-figma": FolderPlusIcon,
  "modal-use-cases": LayersIcon,
  "alert-dialog": OctagonAlertIcon,
  sheet: PanelRightIcon,
  popover: MessageSquareIcon,
  "dropdown-menu": MenuIcon,
  command: CommandIcon,
  breadcrumb: ChevronsRightIcon,
  pagination: EllipsisIcon,
  "navigation-menu": NavigationIcon,
  sidebar: PanelLeftIcon,
}

export function DemoIcon({ id }: { id: string }) {
  return React.createElement(ICONS[id] ?? CircleIcon, { "aria-hidden": true })
}
